modify Allrun.template so that true alpha2_vol at t=0 is taken into account for pbubble

diff --git a/Allrun.template b/Allrun.template
--- a/Allrun.template
+++ b/Allrun.template
@@ -1,4 +1,5 @@
 #!/bin/bash
+pi="3.14159265358979323846264338327950288"
 
 source $HOME/foam/foam-extend-_FOAM_EXTEND_VERSION/etc/bashrc
 
@@ -130,7 +131,6 @@ Uif=_FUNKYSETFIELDS-U_INTERFACE
 
 if [ "_BUBBLE-BOXBUBBLE" = 'true' ];then
     echo "Converting volume to a grid fitting box volume..."
-    pi="3.14159265358979323846264338327950288"
     cellsize=_MESH-CELLSIZE
     sphereVol=$(m4 <<< "esyscmd(perl -e 'printf (   4.*${pi}/3.*(${R})**3  )')")
     if [ "_MESH-MESHDIMS" = "3D" ];then
@@ -230,17 +230,6 @@ then
     fi
     funkySetFields -case . -field U      -expression "0.*vector(0,1,0)" -keepPatches -time $time >> log.setFields 
 
-#     if [ "_BUBBLE-AIMEDRN" != "" ]
-#     then
-#         aimedRn=_BUBBLE-AIMEDRN
-#         pAtMaxNew=$(m4 <<< "esyscmd(perl -e 'printf (   ${pn}*((${aimedRn}**3. - ${beta}*${aimedRn}**3.)/(${RMax}**3. - ${beta}*${aimedRn}**3.))**${gamma}  )')")
-#         echo "pAtRMax_withNewRn= $pAtMaxNew"
-#         #t_transit=_BUBBLE-TTRANSIT
-#         rhoGsource_approx=0.0 #$(m4 <<< "esyscmd(perl -e 'printf (  0.2*${rho_n}*(1.-${aimedRn}**3/${Rn}**3)/${t_transit}  )' )")
-#         echo "rho_gSource      = ${rhoGsource_approx}"
-#         funkySetFields -case . -field rho_gSource -expression "0.5*${rhoGsource_approx}*(1.-tanh(($radial_distance-1.2*${RMax})*5.9/${width}))"\
-#                         -time $time -keepPatches >> log.setFields  #-condition 'pos().x <= 50e-6' 
-#     fi
 
     if [ "_FUNKYSETFIELDS-PRESSUREPROFILE" = "developed" ]
     then
@@ -261,6 +250,19 @@ then
                     -condition "${pVar} < 2.5" >> log.setFields
     else
         echo "---- using theta jump pressure profile ----"
+        get_alpha2_vol_t0 > log.get_alpha2_vol_t0
+        true_alpha2_vol=$(cat 0/alpha2_vol_t0)
+        if [ "_MESH-MESHDIMS" = "2D" ];then
+            if [ ! -e THETA ];then
+                echo "ERROR: alter your meshDict.m4 such that it writes theta into THETA"
+                exit 1
+            fi
+            theta=$(cat THETA)
+            true_alpha2_vol=$(m4 <<< "esyscmd(perl -e 'printf (  $true_alpha2_vol *180./${theta}  )')")
+        fi
+        R=$(m4 <<< "esyscmd(perl -e 'printf (   (${true_alpha2_vol}/(4.*${pi})*3)**(1./3.)  )')")
+        pBubble=$(m4 <<< "esyscmd(perl -e 'printf (   ${pn}*((${Rn}**3. - ${beta}*${Rn}**3.)/(${R}**3. - ${beta}*${Rn}**3.))**${gamma}  )')")
+        echo "pBubble          = $pBubble "
         funkySetFields -case . -field $pVar -expression "${pBubble}*(1.-alpha1)+${pStat}*alpha1"\
                     -time $time -keepPatches >> log.setFields
     fi
